WINDOWS_HOST = "WINDOWS_HOST"
WINDOWS_LOGIN = "WINDOWS_LOGIN"
WINDOWS_PASSWORD = "WINDOWS_PASSWORD"

SHADOW_DEFENDER_PASSWORD = "SHADOW_DEFENDER_PASSWORD"
OBS_REMOTE_URL = "OBS_REMOTE_URL"

DROVA_SERVICE_HOST = "DROVA_SERVICE_HOST"
