WINDOWS_HOST = "WINDOWS_HOST"
WINDOWS_LOGIN = "WINDOWS_LOGIN"
WINDOWS_PASSWORD = "WINDOWS_PASSWORD"

SHADOW_DEFENDER_PASSWORD = "SHADOW_DEFENDER_PASSWORD"
SHADOW_DEFENDER_DRIVES = "SHADOW_DEFENDER_DRIVES"
