worker_processes auto;
rtmp_auto_push on;
events {
    worker_connections 1024;
}

user www-data www-data;

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        max_streams 64;
        
        application live {
            live on;
            record all;
            record_suffix -%Y-%m-%d_%H:%M:%S.flv;
            
            record_path /var/recordings;
        }
    }
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;
    
    server {
        listen 8080;
        server_name localhost;
        
        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        
        location /stat.xsl {
            root /www;
        }
        
        location /recordings {
            alias /var/recordings;
            autoindex on;
        }
    }
}
