#!/bin/bash

### BEGIN INIT INFO
# Provides:             drova_listen
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Drova desktop clearer accounts
### END INIT INFO

set -e

. /lib/lsb/init-functions