#!/bin/bash

### BEGIN INIT INFO
# Provides:             drova_listen
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Drova desktop clearer accounts
### END INIT INFO

set -e

. /lib/lsb/init-functions

PATH=${PATH}:/sbin:~/.local/bin

if [ -z ${DROVA_INSTALL_LOCATION} ]; then
    DROVA_INSTALL_LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. &&  pwd )"
fi

if [ -z ${ENV_LOCATION}]; then
    ENV_LOCATION=${DROVA_INSTALL_LOCATION}/.env
fi

source $ENV_LOCATION

if [ -z ${DROVA_SOCKET_LISTEN} ]; then
    log_failure_msg "Bad DROVA_SOCKET_LISTEN in you env file"
    exit 1
fi

DROVA_PID_FILE=/var/run/drova-desktop-${DROVA_SOCKET_LISTEN}.pid

case "$1" in
    start)
        start-stop-daemon --start --quiet --background --chdir ${DROVA_INSTALL_LOCATION} --pidfile $DROVA_PID_FILE --exec `which poetry` -- run drova_socket
        ;;
    stop)
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $DROVA_PID_FILE
        ;;
    restart)
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $DROVA_PID_FILE
        start-stop-daemon --start --quiet --background --chdir ${DROVA_INSTALL_LOCATION} --pidfile $DROVA_PID_FILE --exec `which poetry` -- run drova_socket
        ;;
    status)
        status_of_proc -p $RSYNC_PID_FILE poerty run drova_socket
        exit $? # notreached due to set -e
        ;;
    *)
        echo "Usage: /etc/init.d/rsync {start|stop|restart|status}"
        exit 1
esac